spring:
  cloud:
    gateway:
      routes:
        - id: baeldung_route
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung/
management:
  endpoints:
    web:
      exposure:
        include: '*'